### ISSUE TITLE
Bulk API error

### ISSUE THREAD

**Issue by korakot** [graphaelli/ipython-elasticsearch#2]
To insert many documents using Bulk API, the last line must include newline "\n".
However this code remove the last newline:
`            body = cell[line1:].strip()`
Is the strip necessary? If you just need to remove a possible empty line at the front, we can use lstrip() insteaed.

**Comment by korakot** [comment]
It still doesn't work. May need elasticsearch.helpers.bulk()

**Comment by graphaelli** [comment]
Sorry, I never saw this issue come in!  closed by c683c35c73423be6a2e74e359bdcfd0cdeb3bf26
